### ISSUE TITLE
Problem w/ bot

### ISSUE THREAD

**Issue by Aestrocorp** [hardlydifficult/HardlyBot#1]
Don't have a million points right now? Why is that? -Anonymous ;)

**Comment by TheSyxe** [comment]
Rip points

**Comment by Aestrocorp** [comment]
KappaPride

**Comment by TheSyxe** [comment]
Sober sucks and is ignoring us

**Comment by Aestrocorp** [comment]
So slow...

**Comment by TheSyxe** [comment]
Fix our issue senpai

**Comment by Aestrocorp** [comment]
IN COMMENT BAR DOWN HERE

**Comment by Aestrocorp** [comment]
ITS CLOSE ISSUE NEXT TO COMMENT BUTTON

**Comment by HardlyDifficult** [comment]
haha.  Found it!

**Comment by Aestrocorp** [comment]
Closed means fixed or ignored for stupidity
