### ISSUE TITLE
Blackjack: Dealer does not peak when an Ace is showing.

### ISSUE THREAD

**Issue by HardlyDifficult** [hardlydifficult/HardlyBot#2]
This legitimately changes the odds... e.g. someone may double down.

**Comment by Aestrocorp** [comment]
Hardly Sober doesn't know how 2 progrem

**Comment by Aestrocorp** [comment]
All he cun do iz 2 pluz tube

**Comment by Aestrocorp** [comment]
YO WEED DON'T EVEN WORK.

**Comment by Aestrocorp** [comment]
I MAKE U INVALID.
TEACH U.
>: DDD

**Comment by HardlyDifficult** [comment]
Done.
