### ISSUE TITLE
Ban spammers

### ISSUE THREAD

**Issue by HardlyDifficult** [hardlydifficult/HardlyBot#29]
If your account is less than 1 week(?) and the first thing you say in chat has a link -> ban.

Other checks
- Spammers won't be following the streamer
- Spammers likely were only in the room for seconds before posting.

**Comment by DatBrick** [comment]
the api to get channel creation time is https://api.twitch.tv/kraken/channels/hardlysober

**Comment by hardlydifficult** [comment]
FYI getting the users creation time is already implemented via Twitch.GetUserFromName which downloads the info if not already cached in SQL.
