### ISSUE TITLE
Not issue but implementation

### ISSUE THREAD

**Issue by Aestrocorp** [hardlydifficult/HardlyBot#31]
I want to add a Strawpoll getter, what you do is type in !getvote {poll number}, and it prints the winner. I don't know how to implement this into YOUR bot, but since it's already done then I would guess it's pretty simple, the code is below:

http://pastebin.com/E58HtZ1k

By the way, use the getWinner() method in order to actually get the winner, it should return a string that says the winner and the amount of votes made for that option in the poll.

**Comment by HardlyDifficult** [comment]
Integrated  - thanks!
