### ISSUE TITLE
Russian Roulette

### ISSUE THREAD

**Issue by swedishwb** [hardlydifficult/HardlyBot#37]
User> !russianroulette for 1 gram.
Bot> Russian Roulette - !joinroulette to play, 1 gram to join.  Winner takes all.
At least 2 people join (max 6).  Then timer to start.
Bot> Russian Roulette has begun - Gun loaded and handed to S_______.  !pullthetrigger or !pussyout
- !pussyout means lose money but no timeout risk
- !pullthetrigger, either you remain in the game or you lose and get a timeout of 1 min.
  User> !pullthetrigger
  Bot> Click... S____ hands the gun to durpy001.  !pullthetrigger or !pussyout
  User> !pullsthetrigger
  Bot> BANG.  S___ wins 1 gram.
  ---- durpy gets a timeout.

---

States
- Off (!russianroulette <amount> to start game)
- Accepting players
- Playing

**Comment by hardlydifficult** [comment]
...or Russian Roulette for a permaban.

**Comment by HardlyDifficult** [comment]
Done.
