### ISSUE TITLE
Hearthstone: Got player names backwards

### ISSUE THREAD

**Issue by HardlyDifficult** [hardlydifficult/HardlyBot#38]
soberBOT: Hearthstone --- just started a new game: Hatredestiny vs HardlySober

**Comment by theBuildr45** [comment]
Did the hearthstone file display it like that?

**Comment by HardlyDifficult** [comment]
I think it's because I incorrectly assumed controller=1 is the current player.  Needs research.

**Comment by HardlyDifficult** [comment]
D 19:49:17.6941416 GameState.DebugPrintPower() - TAG_CHANGE Entity=Hatredestiny tag=CONTROLLER value=1

D 19:49:17.6936414 GameState.DebugPrintPower() - TAG_CHANGE Entity=HardlySober tag=CONTROLLER value=2

... also confirmed that the current player is not always listed first.  Back to the drawing board... may need to store streamer name(s)
