### ISSUE TITLE
BlackJack: Cannot !cancelplay

### ISSUE THREAD

**Issue by TheSyxe** [hardlydifficult/HardlyBot#45]
7:00 TheSyxe: !cancelplay
7:00 soberBOTTheSyxe: You're out, later dude.
7:00 soberBOT: Blackjack: Dealer [K♡] 🂠 , HardlySober [3♡][J♡], TheSyxe [9♤][10♡], durpy001 [4♧][Q♧], dibs09 [8♢][Q♢] -- !Hit, !Stand, !Split or !DoubleDown?

**Comment by HardlyDifficult** [comment]
fixed.
