### ISSUE TITLE
TwitchGameStateMachine race condition - Timers firing when should be closed.

### ISSUE THREAD

**Issue by HardlyDifficult** [hardlydifficult/HardlyBot#48]
I don't know what to do... HELP

**Comment by hardlydifficult** [comment]
I don't know what to do.... HELP

**Comment by HardlyDifficult** [comment]
It seems the game state is correct, just bad messaging from timers. Could wrap with isCorrectState check but that masks the real issue it seems.

**Comment by HardlyDifficult** [comment]
Fixed, I believe.  

I added another lock.  It seems Open was being called after Closed which would explain the timer issue.  Adding the isClosed= check to GameState didn't seem to matter, but the lock there may have corrected our problem.
